name: Build and Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install jupyter-book

      - name: Create book and copy notebook
        run: |
          rm -rf ffhs-book
          jupyter-book create ffhs-book
          mkdir -p ffhs-book/content
          cp onlyAnalysis_ernaehrung.ipynb ffhs-book/content/
          echo "format: jb-book" > ffhs-book/_toc.yml
          echo "root: onlyanalysis_ernaehrung" >> ffhs-book/_toc.yml


      - name: Build Jupyter Book
        run: jupyter-book build ffhs-book

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ffhs-book/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
